# Generated by Django 3.2.12 on 2024-04-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0003_userrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='description',
        ),
    ]
