# Generated by Django 3.2.12 on 2024-04-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0005_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tatus',
            field=models.BooleanField(default=False),
        ),
    ]
