# Generated by Django 3.2.12 on 2024-04-07 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0006_user_tatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tatus',
            new_name='Status',
        ),
    ]
